"""`LedgerEntryRepository` — app/repositories/ledger_entry.py.

`ledger_entry` is append-only. Not "by convention", not "enforced in the service layer" —
there is a `BEFORE UPDATE OR DELETE` trigger from migration 0004 that raises P0001, and the
tests below fire it deliberately, because a trigger nobody ever triggers in CI is a trigger
that quietly stops existing after somebody's autogenerated migration.

Corrections are made by posting a compensating `reversal` transaction. That is also why
migration 0020 could quarantine the incident's 1,847 duplicates but could not delete them.
"""

from __future__ import annotations

import pytest
from sqlalchemy import text
from sqlalchemy.exc import DBAPIError, IntegrityError

from app.models.ledger_entry import LedgerEntry
from app.repositories.ledger_entry import LedgerEntryRepository
from app.repositories.ledger_transaction import LedgerTransactionRepository
from tests.factories import make_account_set

pytestmark = [pytest.mark.integration, pytest.mark.asyncio]


@pytest.fixture
def repo() -> LedgerEntryRepository:
    return LedgerEntryRepository()


async def _seed_transaction(session, txn_id: str = "txn_le_1") -> tuple[str, list[str]]:
    from app.models.ledger_transaction import LedgerTransaction

    accounts = make_account_set(merchant_id="mer_le_1", currency="USD", livemode=True)
    for account in accounts:
        session.add(account)

    await LedgerTransactionRepository().add(
        session,
        LedgerTransaction(
            id=txn_id,
            idempotency_key=f"settle:sb_LE:{txn_id}",
            request_fingerprint="d" * 64,
            purpose="settle",
            merchant_id="mer_le_1",
            currency="USD",
            livemode=True,
            reference_type="reconciliation_item",
            reference_id="ri_le_1",
            created_by="reconciliation",
        ),
    )
    await session.flush()
    return txn_id, [a.id for a in accounts]


def _entry(txn_id: str, account_id: str, direction: str, amount: int, seq: int) -> LedgerEntry:
    return LedgerEntry(
        id=f"le_{txn_id}_{seq}",
        transaction_id=txn_id,
        account_id=account_id,
        direction=direction,
        amount_minor=amount,
        currency="USD",
        livemode=True,
        sequence=seq,
    )


async def test_add_all_writes_the_whole_leg_set(session, repo: LedgerEntryRepository) -> None:
    txn_id, accounts = await _seed_transaction(session, "txn_le_add")

    await repo.add_all(
        session,
        [
            _entry(txn_id, accounts[0], "debit", 10_000, 0),
            _entry(txn_id, accounts[1], "credit", 10_000, 1),
        ],
    )
    await session.flush()

    entries = await repo.list_for_transaction(session, txn_id)
    assert len(entries) == 2
    assert [e.sequence for e in entries] == [0, 1]


async def test_sequence_is_unique_within_a_transaction(session, repo: LedgerEntryRepository) -> None:
    txn_id, accounts = await _seed_transaction(session, "txn_le_seq")

    await repo.add_all(session, [_entry(txn_id, accounts[0], "debit", 100, 0)])
    await session.flush()
    await repo.add_all(session, [_entry(txn_id, accounts[1], "credit", 100, 0)])

    with pytest.raises(IntegrityError):
        await session.flush()


async def test_amount_must_be_positive(session, repo: LedgerEntryRepository) -> None:
    # Direction carries the sign; the check constraint is the database's opinion on that.
    txn_id, accounts = await _seed_transaction(session, "txn_le_neg")
    await repo.add_all(session, [_entry(txn_id, accounts[0], "debit", -1, 0)])

    with pytest.raises(IntegrityError):
        await session.flush()


async def test_update_is_blocked_by_the_append_only_trigger(session) -> None:
    txn_id, accounts = await _seed_transaction(session, "txn_le_upd")
    session.add(_entry(txn_id, accounts[0], "debit", 500, 0))
    await session.flush()

    with pytest.raises(DBAPIError) as excinfo:
        await session.execute(
            text("UPDATE ledger_entry SET amount_minor = 1 WHERE transaction_id = :t"),
            {"t": txn_id},
        )

    assert "append-only" in str(excinfo.value)


async def test_delete_is_blocked_by_the_append_only_trigger(session) -> None:
    txn_id, accounts = await _seed_transaction(session, "txn_le_del")
    session.add(_entry(txn_id, accounts[0], "debit", 500, 0))
    await session.flush()

    with pytest.raises(DBAPIError) as excinfo:
        await session.execute(
            text("DELETE FROM ledger_entry WHERE transaction_id = :t"), {"t": txn_id}
        )

    assert "append-only" in str(excinfo.value)


async def test_sum_by_account_and_purpose(session, repo: LedgerEntryRepository) -> None:
    """arc PERF's index lives under this query (`ix_ledger_entry_account_created`).

    It is the hot half of `PayoutCalculator.compute_available`, which is why it got its own
    migration in month 7 rather than waiting for someone to complain twice.
    """
    txn_id, accounts = await _seed_transaction(session, "txn_le_sum")
    payable = accounts[1]

    await repo.add_all(
        session,
        [
            _entry(txn_id, accounts[0], "debit", 10_000, 0),
            _entry(txn_id, payable, "credit", 10_000, 1),
        ],
    )
    await session.flush()

    total = await repo.sum_by_account_and_purpose(
        session, account_id=payable, purpose="settle", direction="credit"
    )
    assert total == 10_000


async def test_trial_balance_by_currency_nets_to_zero(session, repo: LedgerEntryRepository) -> None:
    """LedgerAuditJob invariant 1.

    Worth remembering what this check did NOT catch on the night of PAY-2041: a duplicate
    settlement is internally balanced, so the trial balance passed while the merchant
    payable was overstated by $1.42M. That sentence is the most quoted line in the
    postmortem and the reason invariant 6 exists.
    """
    txn_id, accounts = await _seed_transaction(session, "txn_le_tb")
    await repo.add_all(
        session,
        [
            _entry(txn_id, accounts[0], "debit", 7_777, 0),
            _entry(txn_id, accounts[1], "credit", 7_777, 1),
        ],
    )
    await session.flush()

    balances = await repo.trial_balance_by_currency(session, currency="USD", livemode=True)

    assert sum(row.debit_minor - row.credit_minor for row in balances) == 0
